u32 frameBreak = 100000000;

void PlayAnimation(int animationID){
    if (animationID == 1){
        printf("\033[32m");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("------------------------------------------------\n");
        printf("------------------------------------------------\n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("------------------------------------------------\n");
        printf("                                                \n");
        printf("------------------------------------------------\n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("------------------------------------------------\n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("------------------------------------------------\n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("                                                \n");
        printf("                                                \n");
        printf("------------------------------------------------\n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("------------------------------------------------\n");
        printf("                                                \n");
        printf("                                                \n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("                                                \n");
        printf("------------------------------------------------\n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("------------------------------------------------\n");
        printf("                                                \n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("                                                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                       ||                       \n");
        printf("                       ||                       \n");
        printf("                       ||                       \n");
        printf("                       ||                       \n");
        printf("                       ||                       \n");
        printf("                       ||                       \n");
        printf("                       ||                       \n");
        printf("                       ||                       \n");
        printf("                       ||                       \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                      |  |                      \n");
        printf("                      |  |                      \n");
        printf("                      |  |                      \n");
        printf("                      |  |                      \n");
        printf("                      |  |                      \n");
        printf("                      |  |                      \n");
        printf("                      |  |                      \n");
        printf("                      |  |                      \n");
        printf("                      |  |                      \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                     |    |                     \n");
        printf("                     |    |                     \n");
        printf("                     |    |                     \n");
        printf("                     |    |                     \n");
        printf("                     |    |                     \n");
        printf("                     |    |                     \n");
        printf("                     |    |                     \n");
        printf("                     |    |                     \n");
        printf("                     |    |                     \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                    |      |                    \n");
        printf("                    |      |                    \n");
        printf("                    |      |                    \n");
        printf("                    |      |                    \n");
        printf("                    |      |                    \n");
        printf("                    |      |                    \n");
        printf("                    |      |                    \n");
        printf("                    |      |                    \n");
        printf("                    |      |                    \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                   |        |                   \n");
        printf("                   |        |                   \n");
        printf("                   |        |                   \n");
        printf("                   |        |                   \n");
        printf("                   |        |                   \n");
        printf("                   |        |                   \n");
        printf("                   |        |                   \n");
        printf("                   |        |                   \n");
        printf("                   |        |                   \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                  |          |                  \n");
        printf("                  |          |                  \n");
        printf("                  |          |                  \n");
        printf("                  |          |                  \n");
        printf("                  |          |                  \n");
        printf("                  |          |                  \n");
        printf("                  |          |                  \n");
        printf("                  |          |                  \n");
        printf("                  |          |                  \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                 |            |                 \n");
        printf("                 |            |                 \n");
        printf("                 |            |                 \n");
        printf("                 |            |                 \n");
        printf("                 |            |                 \n");
        printf("                 |            |                 \n");
        printf("                 |            |                 \n");
        printf("                 |            |                 \n");
        printf("                 |            |                 \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |-             |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |--            |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |---           |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |----          |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |-----         |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |------        |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |-------       |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |--------      |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |---------     |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |----------    |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |-----------   |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |------------  |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |------------  |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |------------- |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("            High|--------------|Tide            \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("            High|--------------|Tide            \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("            High|--------------|Tide            \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("            High|--------------|Tide            \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("            High|--------------|Tide            \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("            High|--------------|Tide            \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("            High|--------------|Tide            \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("            High|--------------|Tide            \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("            High|--------------|Tide            \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("            High|--------------|Tide            \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("            High|--------------|Tide            \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("            High|--------------|Tide            \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("            High|--------------|Tide            \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("            High|--------------|Tide            \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("            High|--------------|Tide            \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("            High|--------------|Tide            \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("            High|--------------|Tide            \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("            High|--------------|Tide            \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("            High|--------------|Tide            \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("            High|--------------|Tide            \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("            High|--------------|Tide            \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("            High|--------------|Tide            \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("            High|--------------|Tide            \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("            High|--------------|Tide            \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("            High|--------------|Tide            \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("            High|--------------|Tide            \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("            High|--------------|Tide            \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("            High|--------------|Tide            \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("            High|--------------|Tide            \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("            High|--------------|Tide            \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("            High|--------------|Tide            \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("            High|--------------|Tide            \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("            High|--------------|Tide            \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("            High|--------------|Tide            \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("            High|--------------|Tide            \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("            High|--------------|Tide            \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("            High|--------------|Tide            \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("            High|--------------|Tide            \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("            High|--------------|Tide            \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("            High|--------------|Tide            \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("            High|--------------|Tide            \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("            High|--------------|Tide            \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("            High|--------------|Tide            \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("            High|--------------|Tide            \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
        printf("------------------------------------------------\n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("            High|--------------|Tide            \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("                |              |                \n");
        printf("------------------------------------------------\n");svcSleepThread(frameBreak);consoleClear();
        // --------------------------------------------------------
    }
}