u32 terminalPrintDelay = 50000000;

AnimationHidden(int mode){
    if (mode == 0){
        printf("\033[32m                        x                         \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32m                        x                         \033[0m\n");
		printf("\033[32m                        x                         \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32m                        x                         \033[0m\n");
		printf("\033[32m                        x                         \033[0m\n");
		printf("\033[32m                        x                         \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32m                        x                         \033[0m\n");
		printf("\033[32m                        x                         \033[0m\n");
		printf("\033[32m                       x x                        \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32m                        x                         \033[0m\n");
		printf("\033[32m                       x x                        \033[0m\n");
		printf("\033[32m                      x   x                       \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32m                        x                         \033[0m\n");
		printf("\033[32m                       x x                        \033[0m\n");
		printf("\033[32m                      x   x                       \033[0m\n");
		printf("\033[32m                     X     X                      \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32m                        x                         \033[0m\n");
		printf("\033[32m                       x x                        \033[0m\n");
		printf("\033[32m                      x   x                       \033[0m\n");
		printf("\033[32m                     X     X                      \033[0m\n");
		printf("\033[32m                      x   x                       \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32m                        x                         \033[0m\n");
		printf("\033[32m                       x x                        \033[0m\n");
		printf("\033[32m                      x   x                       \033[0m\n");
		printf("\033[32m                     X     X                      \033[0m\n");
		printf("\033[32m                      x   x                       \033[0m\n");
		printf("\033[32m                       x x                        \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32m                        x                         \033[0m\n");
		printf("\033[32m                       x x                        \033[0m\n");
		printf("\033[32m                      x   x                       \033[0m\n");
		printf("\033[32m                     X     X                      \033[0m\n");
		printf("\033[32m                      x   x                       \033[0m\n");
		printf("\033[32m                       x x                        \033[0m\n");
		printf("\033[32m                        x                         \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32m                        o                         \033[0m\n");
		printf("\033[32m                       x x                        \033[0m\n");
		printf("\033[32m                      x   x                       \033[0m\n");
		printf("\033[32m                     X     X                      \033[0m\n");
		printf("\033[32m                      x   x                       \033[0m\n");
		printf("\033[32m                       x x                        \033[0m\n");
		printf("\033[32m                        x                         \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32m                        O                         \033[0m\n");
		printf("\033[32m                       o o                        \033[0m\n");
		printf("\033[32m                      x   x                       \033[0m\n");
		printf("\033[32m                     X     X                      \033[0m\n");
		printf("\033[32m                      x   x                       \033[0m\n");
		printf("\033[32m                       x x                        \033[0m\n");
		printf("\033[32m                        x                         \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32m                        O                         \033[0m\n");
		printf("\033[32m                       O O                        \033[0m\n");
		printf("\033[32m                      o   o                       \033[0m\n");
		printf("\033[32m                     X     X                      \033[0m\n");
		printf("\033[32m                      x   x                       \033[0m\n");
		printf("\033[32m                       x x                        \033[0m\n");
		printf("\033[32m                        x                         \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32m                        O                         \033[0m\n");
		printf("\033[32m                       O O                        \033[0m\n");
		printf("\033[32m                      O   O                       \033[0m\n");
		printf("\033[32m                     o     o                      \033[0m\n");
		printf("\033[32m                      x   x                       \033[0m\n");
		printf("\033[32m                       x x                        \033[0m\n");
		printf("\033[32m                        x                         \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32m                        O                         \033[0m\n");
		printf("\033[32m                       O O                        \033[0m\n");
		printf("\033[32m                      O   O                       \033[0m\n");
		printf("\033[32m                     O     O                      \033[0m\n");
		printf("\033[32m                      o   o                       \033[0m\n");
		printf("\033[32m                       x x                        \033[0m\n");
		printf("\033[32m                        x                         \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32m                        O                         \033[0m\n");
		printf("\033[32m                       O O                        \033[0m\n");
		printf("\033[32m                      O   O                       \033[0m\n");
		printf("\033[32m                     O     O                      \033[0m\n");
		printf("\033[32m                      O   O                       \033[0m\n");
		printf("\033[32m                       o o                        \033[0m\n");
		printf("\033[32m                        x                         \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32m                        O                         \033[0m\n");
		printf("\033[32m                       O O                        \033[0m\n");
		printf("\033[32m                      O   O                       \033[0m\n");
		printf("\033[32m                     O     O                      \033[0m\n");
		printf("\033[32m                      O   O                       \033[0m\n");
		printf("\033[32m                       O O                        \033[0m\n");
		printf("\033[32m                        o                         \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32m                        O                         \033[0m\n");
		printf("\033[32m                       O O                        \033[0m\n");
		printf("\033[32m                      O   O                       \033[0m\n");
		printf("\033[32m                     O     O                      \033[0m\n");
		printf("\033[32m                      O   O                       \033[0m\n");
		printf("\033[32m                       O O                        \033[0m\n");
		printf("\033[32m                        O                         \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32m                        O                         \033[0m\n");
		printf("\033[32m                       O O                        \033[0m\n");
		printf("\033[32m                      O   O                       \033[0m\n");
		printf("\033[32m                     O     O                      \033[0m\n");
		printf("\033[32m                      O   O                       \033[0m\n");
		printf("\033[32m                       O O                        \033[0m\n");
		printf("\033[32m                        O                         \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32m                        O                         \033[0m\n");
		printf("\033[32m                       O O                        \033[0m\n");
		printf("\033[32m                      O   O                       \033[0m\n");
		printf("\033[32m                     O     O                      \033[0m\n");
		printf("\033[32m                      O   O                       \033[0m\n");
		printf("\033[32m                       O O                        \033[0m\n");
		printf("\033[32m                        O                         \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32m                        O                         \033[0m\n");
		printf("\033[32m                       O O                        \033[0m\n");
		printf("\033[32m                      O   O                       \033[0m\n");
		printf("\033[32m                     O     O                      \033[0m\n");
		printf("\033[32m                      O   O                       \033[0m\n");
		printf("\033[32m                       O O                        \033[0m\n");
		printf("\033[32m                        O                         \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32m                        O                         \033[0m\n");
		printf("\033[32m                       O O                        \033[0m\n");
		printf("\033[32m                      O   O                       \033[0m\n");
		printf("\033[32m                     O     O                      \033[0m\n");
		printf("\033[32m                      O   O                       \033[0m\n");
		printf("\033[32m                       O O                        \033[0m\n");
		printf("\033[32m                        O                         \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32m                        O                         \033[0m\n");
		printf("\033[32m                       O O                        \033[0m\n");
		printf("\033[32m                      O   O                       \033[0m\n");
		printf("\033[32m                     O     O                      \033[0m\n");
		printf("\033[32m                      O   O                       \033[0m\n");
		printf("\033[32m                       O O                        \033[0m\n");
		printf("\033[32m                        O                         \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32m                        O                         \033[0m\n");
		printf("\033[32m                       O O                        \033[0m\n");
		printf("\033[32m                      O   O                       \033[0m\n");
		printf("\033[32m                     O     O                      \033[0m\n");
		printf("\033[32m                      O   O                       \033[0m\n");
		printf("\033[32m                       O O                        \033[0m\n");
		printf("\033[32m                        O                         \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32m                        O                         \033[0m\n");
		printf("\033[32m                       O O                        \033[0m\n");
		printf("\033[32m                      O   O                       \033[0m\n");
		printf("\033[32m                     O     O                      \033[0m\n");
		printf("\033[32m                      O   O                       \033[0m\n");
		printf("\033[32m                       O O                        \033[0m\n");
		printf("\033[32m                        O                         \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                        X                         \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32m                        O                         \033[0m\n");
		printf("\033[32m                       O O                        \033[0m\n");
		printf("\033[32m                      O   O                       \033[0m\n");
		printf("\033[32m                     O     O                      \033[0m\n");
		printf("\033[32m                      O   O                       \033[0m\n");
		printf("\033[32m                       O O                        \033[0m\n");
		printf("\033[32m                        O                         \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                        X                         \033[0m\n");
		printf("\033[32m                       XXX                        \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32m                        O                         \033[0m\n");
		printf("\033[32m                       O O                        \033[0m\n");
		printf("\033[32m                      O   O                       \033[0m\n");
		printf("\033[32m                     O     O                      \033[0m\n");
		printf("\033[32m                      O   O                       \033[0m\n");
		printf("\033[32m                       O O                        \033[0m\n");
		printf("\033[32m                        O                         \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                        X                         \033[0m\n");
		printf("\033[32m                       XXX                        \033[0m\n");
		printf("\033[32m                      XXXXX                       \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32m                        O                         \033[0m\n");
		printf("\033[32m                       O O                        \033[0m\n");
		printf("\033[32m                      O   O                       \033[0m\n");
		printf("\033[32m                     O     O                      \033[0m\n");
		printf("\033[32m                      O   O                       \033[0m\n");
		printf("\033[32m                       O O                        \033[0m\n");
		printf("\033[32m                        O                         \033[0m\n");
		printf("\033[32m                        X                         \033[0m\n");
		printf("\033[32m                       XXX                        \033[0m\n");
		printf("\033[32m                      XXXXX                       \033[0m\n");
		printf("\033[32m                     XXXXXXX                      \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32m                        O                         \033[0m\n");
		printf("\033[32m                       O O                        \033[0m\n");
		printf("\033[32m                      O   O                       \033[0m\n");
		printf("\033[32m                     O     O                      \033[0m\n");
		printf("\033[32m                      O   O                       \033[0m\n");
		printf("\033[32m                       O O                        \033[0m\n");
		printf("\033[32m                        X                         \033[0m\n");
		printf("\033[32m                       XXX                        \033[0m\n");
		printf("\033[32m                      XXXXX                       \033[0m\n");
		printf("\033[32m                     XXXXXXX                      \033[0m\n");
		printf("\033[32m                    XXXXXXXXX                     \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32m                        O                         \033[0m\n");
		printf("\033[32m                       O O                        \033[0m\n");
		printf("\033[32m                      O   O                       \033[0m\n");
		printf("\033[32m                     O     O                      \033[0m\n");
		printf("\033[32m                      O   O                       \033[0m\n");
		printf("\033[32m                       OXO                        \033[0m\n");
		printf("\033[32m                       XXX                        \033[0m\n");
		printf("\033[32m                      XXXXX                       \033[0m\n");
		printf("\033[32m                     XXXXXXX                      \033[0m\n");
		printf("\033[32m                    XXXXXXXXX                     \033[0m\n");
		printf("\033[32m                   XXXXXXXXXXX                    \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32m                        O                         \033[0m\n");
		printf("\033[32m                       O O                        \033[0m\n");
		printf("\033[32m                      O   O                       \033[0m\n");
		printf("\033[32m                     O     O                      \033[0m\n");
		printf("\033[32m                      O X O                       \033[0m\n");
		printf("\033[32m                       XXX                        \033[0m\n");
		printf("\033[32m                      XXXXX                       \033[0m\n");
		printf("\033[32m                     XXXXXXX                      \033[0m\n");
		printf("\033[32m                    XXXXXXXXX                     \033[0m\n");
		printf("\033[32m                   XXXXXXXXXXX                    \033[0m\n");
		printf("\033[32m                  XXXXXXXXXXXXX                   \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32m                        O                         \033[0m\n");
		printf("\033[32m                       O O                        \033[0m\n");
		printf("\033[32m                      O   O                       \033[0m\n");
		printf("\033[32m                     O  X  O                      \033[0m\n");
		printf("\033[32m                      OXXXO                       \033[0m\n");
		printf("\033[32m                      XXXXX                       \033[0m\n");
		printf("\033[32m                     XXXXXXX                      \033[0m\n");
		printf("\033[32m                    XXXXXXXXX                     \033[0m\n");
		printf("\033[32m                   XXXXXXXXXXX                    \033[0m\n");
		printf("\033[32m                  XXXXXXXXXXXXX                   \033[0m\n");
		printf("\033[32m                 XXXXXXXXXXXXXXX                  \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32m                        O                         \033[0m\n");
		printf("\033[32m                       O O                        \033[0m\n");
		printf("\033[32m                      O X O                       \033[0m\n");
		printf("\033[32m                     O XXX O                      \033[0m\n");
		printf("\033[32m                      XXXXX                       \033[0m\n");
		printf("\033[32m                     XXXXXXX                      \033[0m\n");
		printf("\033[32m                    XXXXXXXXX                     \033[0m\n");
		printf("\033[32m                   XXXXXXXXXXX                    \033[0m\n");
		printf("\033[32m                  XXXXXXXXXXXXX                   \033[0m\n");
		printf("\033[32m                 XXXXXXXXXXXXXXX                  \033[0m\n");
		printf("\033[32m                XXXXXXXXXXXXXXXXX                 \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32m                        O                         \033[0m\n");
		printf("\033[32m                       OXO                        \033[0m\n");
		printf("\033[32m                      OXXXO                       \033[0m\n");
		printf("\033[32m                     OXXXXXO                      \033[0m\n");
		printf("\033[32m                     XXXXXXX                      \033[0m\n");
		printf("\033[32m                    XXXXXXXXX                     \033[0m\n");
		printf("\033[32m                   XXXXXXXXXXX                    \033[0m\n");
		printf("\033[32m                  XXXXXXXXXXXXX                   \033[0m\n");
		printf("\033[32m                 XXXXXXXXXXXXXXX                  \033[0m\n");
		printf("\033[32m                XXXXXXXXXXXXXXXXX                 \033[0m\n");
		printf("\033[32m               XXXXXXXXXXXXXXXXXXX                \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32m                        X                         \033[0m\n");
		printf("\033[32m                       XXX                        \033[0m\n");
		printf("\033[32m                      XXXXX                       \033[0m\n");
		printf("\033[32m                     XXXXXXX                      \033[0m\n");
		printf("\033[32m                    XXXXXXXXX                     \033[0m\n");
		printf("\033[32m                   XXXXXXXXXXX                    \033[0m\n");
		printf("\033[32m                  XXXXXXXXXXXXX                   \033[0m\n");
		printf("\033[32m                 XXXXXXXXXXXXXXX                  \033[0m\n");
		printf("\033[32m                XXXXXXXXXXXXXXXXX                 \033[0m\n");
		printf("\033[32m               XXXXXXXXXXXXXXXXXXX                \033[0m\n");
		printf("\033[32m              XXXXXXXXXXXXXXXXXXXXX               \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32m                       XXX                        \033[0m\n");
		printf("\033[32m                      XXXXX                       \033[0m\n");
		printf("\033[32m                     XXXXXXX                      \033[0m\n");
		printf("\033[32m                    XXXXXXXXX                     \033[0m\n");
		printf("\033[32m                   XXXXXXXXXXX                    \033[0m\n");
		printf("\033[32m                  XXXXXXXXXXXXX                   \033[0m\n");
		printf("\033[32m                 XXXXXXXXXXXXXXX                  \033[0m\n");
		printf("\033[32m                XXXXXXXXXXXXXXXXX                 \033[0m\n");
		printf("\033[32m               XXXXXXXXXXXXXXXXXXX                \033[0m\n");
		printf("\033[32m              XXXXXXXXXXXXXXXXXXXXX               \033[0m\n");
		printf("\033[32m             XXXXXXXXXXXXXXXXXXXXXXX              \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32m                      XXXXX                       \033[0m\n");
		printf("\033[32m                     XXXXXXX                      \033[0m\n");
		printf("\033[32m                    XXXXXXXXX                     \033[0m\n");
		printf("\033[32m                   XXXXXXXXXXX                    \033[0m\n");
		printf("\033[32m                  XXXXXXXXXXXXX                   \033[0m\n");
		printf("\033[32m                 XXXXXXXXXXXXXXX                  \033[0m\n");
		printf("\033[32m                XXXXXXXXXXXXXXXXX                 \033[0m\n");
		printf("\033[32m               XXXXXXXXXXXXXXXXXXX                \033[0m\n");
		printf("\033[32m              XXXXXXXXXXXXXXXXXXXXX               \033[0m\n");
		printf("\033[32m             XXXXXXXXXXXXXXXXXXXXXXX              \033[0m\n");
		printf("\033[32m            XXXXXXXXXXXXXXXXXXXXXXXXX             \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32m                     XXXXXXX                      \033[0m\n");
		printf("\033[32m                    XXXXXXXXX                     \033[0m\n");
		printf("\033[32m                   XXXXXXXXXXX                    \033[0m\n");
		printf("\033[32m                  XXXXXXXXXXXXX                   \033[0m\n");
		printf("\033[32m                 XXXXXXXXXXXXXXX                  \033[0m\n");
		printf("\033[32m                XXXXXXXXXXXXXXXXX                 \033[0m\n");
		printf("\033[32m               XXXXXXXXXXXXXXXXXXX                \033[0m\n");
		printf("\033[32m              XXXXXXXXXXXXXXXXXXXXX               \033[0m\n");
		printf("\033[32m             XXXXXXXXXXXXXXXXXXXXXXX              \033[0m\n");
		printf("\033[32m            XXXXXXXXXXXXXXXXXXXXXXXXX             \033[0m\n");
		printf("\033[32m           XXXXXXXXXXXXXXXXXXXXXXXXXXX            \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32m                    XXXXXXXXX                     \033[0m\n");
		printf("\033[32m                   XXXXXXXXXXX                    \033[0m\n");
		printf("\033[32m                  XXXXXXXXXXXXX                   \033[0m\n");
		printf("\033[32m                 XXXXXXXXXXXXXXX                  \033[0m\n");
		printf("\033[32m                XXXXXXXXXXXXXXXXX                 \033[0m\n");
		printf("\033[32m               XXXXXXXXXXXXXXXXXXX                \033[0m\n");
		printf("\033[32m              XXXXXXXXXXXXXXXXXXXXX               \033[0m\n");
		printf("\033[32m             XXXXXXXXXXXXXXXXXXXXXXX              \033[0m\n");
		printf("\033[32m            XXXXXXXXXXXXXXXXXXXXXXXXX             \033[0m\n");
		printf("\033[32m           XXXXXXXXXXXXXXXXXXXXXXXXXXX            \033[0m\n");
		printf("\033[32m          XXXXXXXXXXXXXXXXXXXXXXXXXXXXX           \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32m                   XXXXXXXXXXX                    \033[0m\n");
		printf("\033[32m                  XXXXXXXXXXXXX                   \033[0m\n");
		printf("\033[32m                 XXXXXXXXXXXXXXX                  \033[0m\n");
		printf("\033[32m                XXXXXXXXXXXXXXXXX                 \033[0m\n");
		printf("\033[32m               XXXXXXXXXXXXXXXXXXX                \033[0m\n");
		printf("\033[32m              XXXXXXXXXXXXXXXXXXXXX               \033[0m\n");
		printf("\033[32m             XXXXXXXXXXXXXXXXXXXXXXX              \033[0m\n");
		printf("\033[32m            XXXXXXXXXXXXXXXXXXXXXXXXX             \033[0m\n");
		printf("\033[32m           XXXXXXXXXXXXXXXXXXXXXXXXXXX            \033[0m\n");
		printf("\033[32m          XXXXXXXXXXXXXXXXXXXXXXXXXXXXX           \033[0m\n");
		printf("\033[32m         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX          \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32mX                 XXXXXXXXXXXXX                   \033[0m\n");
		printf("\033[32m                 XXXXXXXXXXXXXXX                  \033[0m\n");
		printf("\033[32m                XXXXXXXXXXXXXXXXX                 \033[0m\n");
		printf("\033[32m               XXXXXXXXXXXXXXXXXXX                \033[0m\n");
		printf("\033[32m              XXXXXXXXXXXXXXXXXXXXX               \033[0m\n");
		printf("\033[32m             XXXXXXXXXXXXXXXXXXXXXXX              \033[0m\n");
		printf("\033[32m            XXXXXXXXXXXXXXXXXXXXXXXXX             \033[0m\n");
		printf("\033[32m           XXXXXXXXXXXXXXXXXXXXXXXXXXX            \033[0m\n");
		printf("\033[32m          XXXXXXXXXXXXXXXXXXXXXXXXXXXXX           \033[0m\n");
		printf("\033[32m         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX          \033[0m\n");
		printf("\033[32m        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX         \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32mXX               XXXXXXXXXXXXXXX                  \033[0m\n");
		printf("\033[32mX               XXXXXXXXXXXXXXXXX                 \033[0m\n");
		printf("\033[32m               XXXXXXXXXXXXXXXXXXX                \033[0m\n");
		printf("\033[32m              XXXXXXXXXXXXXXXXXXXXX               \033[0m\n");
		printf("\033[32m             XXXXXXXXXXXXXXXXXXXXXXX              \033[0m\n");
		printf("\033[32m            XXXXXXXXXXXXXXXXXXXXXXXXX             \033[0m\n");
		printf("\033[32m           XXXXXXXXXXXXXXXXXXXXXXXXXXX            \033[0m\n");
		printf("\033[32m          XXXXXXXXXXXXXXXXXXXXXXXXXXXXX           \033[0m\n");
		printf("\033[32m         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX          \033[0m\n");
		printf("\033[32m        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX         \033[0m\n");
		printf("\033[32m       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32mXXX             XXXXXXXXXXXXXXXXX                X\033[0m\n");
		printf("\033[32mXX             XXXXXXXXXXXXXXXXXXX                \033[0m\n");
		printf("\033[32mX             XXXXXXXXXXXXXXXXXXXXX               \033[0m\n");
		printf("\033[32m             XXXXXXXXXXXXXXXXXXXXXXX              \033[0m\n");
		printf("\033[32m            XXXXXXXXXXXXXXXXXXXXXXXXX             \033[0m\n");
		printf("\033[32m           XXXXXXXXXXXXXXXXXXXXXXXXXXX            \033[0m\n");
		printf("\033[32m          XXXXXXXXXXXXXXXXXXXXXXXXXXXXX           \033[0m\n");
		printf("\033[32m         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX          \033[0m\n");
		printf("\033[32m        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX         \033[0m\n");
		printf("\033[32m       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        \033[0m\n");
		printf("\033[32m      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX       \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32mXXXX           XXXXXXXXXXXXXXXXXXX              XX\033[0m\n");
		printf("\033[32mXXX           XXXXXXXXXXXXXXXXXXXXX              X\033[0m\n");
		printf("\033[32mXX           XXXXXXXXXXXXXXXXXXXXXXX              \033[0m\n");
		printf("\033[32mX           XXXXXXXXXXXXXXXXXXXXXXXXX             \033[0m\n");
		printf("\033[32m           XXXXXXXXXXXXXXXXXXXXXXXXXXX            \033[0m\n");
		printf("\033[32m          XXXXXXXXXXXXXXXXXXXXXXXXXXXXX           \033[0m\n");
		printf("\033[32m         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX          \033[0m\n");
		printf("\033[32m        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX         \033[0m\n");
		printf("\033[32m       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        \033[0m\n");
		printf("\033[32m      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX       \033[0m\n");
		printf("\033[32m     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX      \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32mXXXXX         XXXXXXXXXXXXXXXXXXXXX            XXX\033[0m\n");
		printf("\033[32mXXXX         XXXXXXXXXXXXXXXXXXXXXXX            XX\033[0m\n");
		printf("\033[32mXXX         XXXXXXXXXXXXXXXXXXXXXXXXX            X\033[0m\n");
		printf("\033[32mXX         XXXXXXXXXXXXXXXXXXXXXXXXXXX            \033[0m\n");
		printf("\033[32mX         XXXXXXXXXXXXXXXXXXXXXXXXXXXXX           \033[0m\n");
		printf("\033[32m         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX          \033[0m\n");
		printf("\033[32m        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX         \033[0m\n");
		printf("\033[32m       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        \033[0m\n");
		printf("\033[32m      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX       \033[0m\n");
		printf("\033[32m     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX      \033[0m\n");
		printf("\033[32m    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX     \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32mXXXXXX       XXXXXXXXXXXXXXXXXXXXXXX          XXXX\033[0m\n");
		printf("\033[32mXXXXX       XXXXXXXXXXXXXXXXXXXXXXXXX          XXX\033[0m\n");
		printf("\033[32mXXXX       XXXXXXXXXXXXXXXXXXXXXXXXXXX          XX\033[0m\n");
		printf("\033[32mXXX       XXXXXXXXXXXXXXXXXXXXXXXXXXXXX          X\033[0m\n");
		printf("\033[32mXX       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX          \033[0m\n");
		printf("\033[32mX       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX         \033[0m\n");
		printf("\033[32m       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        \033[0m\n");
		printf("\033[32m      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX       \033[0m\n");
		printf("\033[32m     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX      \033[0m\n");
		printf("\033[32m    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX     \033[0m\n");
		printf("\033[32m   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32mXXXXXXX     XXXXXXXXXXXXXXXXXXXXXXXXX        XXXXX\033[0m\n");
		printf("\033[32mXXXXXX     XXXXXXXXXXXXXXXXXXXXXXXXXXX        XXXX\033[0m\n");
		printf("\033[32mXXXXX     XXXXXXXXXXXXXXXXXXXXXXXXXXXXX        XXX\033[0m\n");
		printf("\033[32mXXXX     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        XX\033[0m\n");
		printf("\033[32mXXX     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        X\033[0m\n");
		printf("\033[32mXX     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        \033[0m\n");
		printf("\033[32mX     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX       \033[0m\n");
		printf("\033[32m     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX      \033[0m\n");
		printf("\033[32m    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX     \033[0m\n");
		printf("\033[32m   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    \033[0m\n");
		printf("\033[32m  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32mXXXXXXXX   XXXXXXXXXXXXXXXXXXXXXXXXXXX      XXXXXX\033[0m\n");
		printf("\033[32mXXXXXXX   XXXXXXXXXXXXXXXXXXXXXXXXXXXXX      XXXXX\033[0m\n");
		printf("\033[32mXXXXXX   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX      XXXX\033[0m\n");
		printf("\033[32mXXXXX   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX      XXX\033[0m\n");
		printf("\033[32mXXXX   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX      XX\033[0m\n");
		printf("\033[32mXXX   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX      X\033[0m\n");
		printf("\033[32mXX   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX      \033[0m\n");
		printf("\033[32mX   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX     \033[0m\n");
		printf("\033[32m   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    \033[0m\n");
		printf("\033[32m  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   \033[0m\n");
		printf("\033[32m XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32mXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXXX\033[0m\n");
		printf("\033[32mXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXXX\033[0m\n");
		printf("\033[32mXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXXX\033[0m\n");
		printf("\033[32mXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XXX\033[0m\n");
		printf("\033[32mXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    XX\033[0m\n");
		printf("\033[32mXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    X\033[0m\n");
		printf("\033[32mXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    \033[0m\n");
		printf("\033[32mX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   \033[0m\n");
		printf("\033[32m XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  \033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   XXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   XXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   XXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   XXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   XXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   XXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   XX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   X\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   \033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  \033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX \033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32m                                                  \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");
		printf("\033[32m                                                  \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
		//--------------------------------------------------------------------------------------------------------------------------------
		printf("\033[32m                                                    \033[0m\n");
		printf("\033[32m                                                    \033[0m\n");
		printf("\033[32m                                                    \033[0m\n");
		printf("\033[32m                                                    \033[0m\n");
		printf("\033[32m                                                    \033[0m\n");
		printf("\033[32m                                                    \033[0m\n");
		printf("\033[32m                                                    \033[0m\n");
		printf("\033[32m                                                    \033[0m\n");
		printf("\033[32m                                                    \033[0m\n");
		printf("\033[32m                                                    \033[0m\n");
		printf("\033[32m                                                    \033[0m\n");svcSleepThread(terminalPrintDelay);consoleClear();
    }
    else if (mode == 1){
        return;
    }
    else {
        printf("Invalid Option!");
    }
}